export const airlineCodeToName: { [key: string]: string } = {
    'AA': 'American Airlines',
    'AC': 'Air Canada',
    'AF': 'Air France',
    'AI': 'Air India',
    'AK': 'AirAsia',
    'AM': 'Aeromexico',
    'AS': 'Alaska Airlines',
    'AV': 'Avianca',
    'AY': 'Finnair',
    'AZ': 'Alitalia',
    'B6': 'JetBlue Airways',
    'BA': 'British Airways',
    'BR': 'EVA Air',
    'CA': 'Air China',
    'CI': 'China Airlines',
    'CX': 'Cathay Pacific',
    'CZ': 'China Southern Airlines',
    'DL': 'Delta Air Lines',
    'EI': 'Aer Lingus',
    'EK': 'Emirates',
    'ET': 'Ethiopian Airlines',
    'EY': 'Etihad Airways',
    'F9': 'Frontier Airlines',
    'FI': 'Icelandair',
    'FJ': 'Fiji Airways',
    'FR': 'Ryanair',
    'FZ': 'Flydubai',
    'G3': 'GOL Linhas Aéreas',
    'G9': 'Air Arabia',
    'GA': 'Garuda Indonesia',
    'GF': 'Gulf Air',
    'HA': 'Hawaiian Airlines',
    'HU': 'Hainan Airlines',
    'IB': 'Iberia',
    'JJ': 'LATAM Brasil',
    'JL': 'Japan Airlines',
    'KE': 'Korean Air',
    'KL': 'KLM Royal Dutch Airlines',
    'KQ': 'Kenya Airways',
    'LA': 'LATAM Airlines',
    'LH': 'Lufthansa',
    'LO': 'LOT Polish Airlines',
    'LX': 'Swiss International Air Lines',
    'MH': 'Malaysia Airlines',
    'MK': 'Air Mauritius',
    'MS': 'EgyptAir',
    'MU': 'China Eastern Airlines',
    'NH': 'All Nippon Airways',
    'NZ': 'Air New Zealand',
    'OD': 'Malindo Air',
    'OK': 'Czech Airlines',
    'OS': 'Austrian Airlines',
    'OZ': 'Asiana Airlines',
    'PR': 'Philippine Airlines',
    'PS': 'Ukraine International Airlines',
    'QF': 'Qantas',
    'QR': 'Qatar Airways',
    'RJ': 'Royal Jordanian',
    'SA': 'South African Airways',
    'SK': 'Scandinavian Airlines',
    'SQ': 'Singapore Airlines',
    'SU': 'Aeroflot',
    'SV': 'Saudia',
    'TG': 'Thai Airways',
    'TK': 'Turkish Airlines',
    'TP': 'TAP Air Portugal',
    'UA': 'United Airlines',
    'UL': 'SriLankan Airlines',
    'VN': 'Vietnam Airlines',
    'VS': 'Virgin Atlantic',
    'WS': 'WestJet',
    'WY': 'Oman Air',
    'X3': 'TUI fly',
    '3K': 'Jetstar Asia Airways',
    '4M': 'LATAM Argentina',
    '5J': 'Cebu Pacific',
    '6E': 'IndiGo',
    '7C': 'Jeju Air',
    '9W': 'Jet Airways',
    '9M': 'Central Mountain Air'
  };